server:
  port: 10010

spring:
  application:
    name: leyou-zuul

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://thorne5691.cn:10086/eureka

# 使用默认路由规则
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    # 如 zuul:port/api/item/user/1 会路由到 item-service是服务的地址和端口tem-service/item/user/1  i