# 打印自动配置报告
#debug: true

spring:
# 配置数据源
  datasource:
    username: root
    password: whatermelon
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.235.115.158:3306/springboot?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    filters: wall,mergeStat
# 配置redis
  redis:
    host: thorne5691.cn
    port: 6379
    database: 0
# 配置rabbitMQ
  rabbitmq:
    host: thorne5691.cn
    username: guest
    password: guest
    port: 5672
    virtual-host: /
# 发送邮件
  mail:
    username: thorne5691@foxmail.com
    password: tkitxqennqolicjc
    host: smtp.qq.com
# 热部署
  devtools:
    restart:
      enabled: true
      # 需要开启热部署的路径
      additional-path: src/main/java
      exclude: static/**,template/**
  freemarker:
    cache: false

# 应用监控管理
management:
  endpoints:
    web:
      # 踩过的坑
      base-path: /actuator
      exposure:
        include: "*"


