spring:
  profiles:
    active: dev
  # 格式化json
#  jackson:
#    serialization:
#      indent-output: true
# springmvc默认日期格式为yyyy/MM/dd，如果不一致则绑定不到Date对象，前端会报400错误
  mvc:
    date-format: yyyy-MM-dd HH:mm
  freemarker:
    enabled: true
    content-type: text/html
    charset: utf-8
    suffix: .ftl
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    check-template-location: true
    # 暴露spring提供的freemarker宏
    expose-spring-macro-helpers: true
    template-loader-path:
      - classpath:/templates/
# 配置国际化配置文件的基础文件路径
#  messages:
#    basename: static/i18n/message


mybatis-plus:
  mapper-locations:
    - classpath:com/mango/rumen/module/mapper/mapping/*.xml



